### ISSUE TITLE
Error when running any utility

### ISSUE THREAD

**Issue by haydenbleasel** [beskar-co/vs-refraction#1]
Reproduction steps:

1. Install package
2. Open Refraction Settings, enter User ID
3. Highlight code
4. Go to Tools > Refraction > [any utility]
5. Run utility

<img width="510" alt="CleanShot 2023-04-20 at 17 49 20@2x" src="https://user-images.githubusercontent.com/4142719/233495042-4e55f0c1-0010-4f0d-b6a5-eb28e27d3dc3.png">

**Comment by toptaltkech17** [comment]
I've investigated it. it seems it had problem when you wanted to generate the code at the end of the file. it should be fixed in 1.0.1 version. changes are pushed

**Comment by haydenbleasel** [comment]
@toptaltkech17 Awesome, thanks! I had to revert the version commit as the CI/CD script is a little weird and replaces `1.0.0` with `1.0.{version}` but I'll give it a test now.

**Comment by haydenbleasel** [comment]
Confirmed fixed! Launched landing page: https://www.refraction.dev/extensions/vs
